from fpdf import FPDF
import qrcode
import uuid
ticket_id=str(uuid.uuid4())[:8]
qrcode.make(ticket_id).save("qrcode.png")
pdf=FPDF()
pdf.add_page()
pdf.set_text_color(0, 0, 0)
pdf.set_font("Times","B",size=20)
pdf.cell(0,10,"Grand Music Night",ln=True,align="C")
pdf.set_font("Times","B",size=13)
pdf.ln(11)
print('Provide the necessary details now:-')
print('')
name=input('Enter the Full Name: ')
print('')
age=int(input('Enter the Age: '))
print('')
cnumber=input('Enter the Contact Number: ')
print('')
wnumber=input('Enter the Whatsapp Number (For sending the ticket digitally): ')
print('')
email=input('Enter the Email ID (For sending the ticket digitally): ')
print('')
ename='Musical Dream Night With The Beatles'
edate='18-10-2025'
etime='08:30 pm'
evenue='Nazrul Hall, Berhampore, India'
seaty=input('Enter the Type of seat (VIP, Regular or Balcony): ')
print('')
seatnum=input('Enter the Seat Number: ')
print('')
seatpref=input('Enter the Seat preference (like near stage or aisle): ')
print('')
modeofp=input('Enter the Mode of payment (UPI, Card or Cash): ')
print('')
paysts=input('Enter the Payment status (Paid/Unpaid): ')
print('')
pdf.cell(0,10,f"Full Name: {name}",ln=True)
pdf.cell(0,10,f"Age: {age}",ln=True)
pdf.cell(0,10,f"Contact Number: {cnumber}",ln=True)
pdf.cell(0,10,f"Whatsapp Number: {wnumber}",ln=True)
pdf.cell(0,10,f"Email ID: {email}",ln=True)
pdf.cell(0,10,f"Name of the musical function: {ename}",ln=True)
pdf.cell(0,10,f"Date of the musical function: {edate}",ln=True)
pdf.cell(0,10,f"Time of the musical function: {etime}",ln=True)
pdf.cell(0,10,f"Venue/Location of the musical function: {evenue}",ln=True)
pdf.cell(0,10,f"Type of seat: {seaty}",ln=True)
pdf.cell(0,10,f"Seat Number: {seatnum}",ln=True)
pdf.cell(0,10,f"Seat preference: {seatpref}",ln=True)
pdf.cell(0,10,f"Mode of payment: {modeofp}",ln=True)
pdf.cell(0,10,f"Payment status: {paysts}",ln=True)
pdf.cell(0,10,f"Ticket ID: {ticket_id}",ln=True)
pdf.image("qrcode.png",x=150,y=10,w=40)
pdf.output("ticket.pdf")
print('Ticket Generated ✅, please check :)')